Re-rendered the standard library, which now contains matchers for higher meta-levels.

diff --git a/test/make-sure-everything-works b/test/make-sure-everything-works
--- a/test/make-sure-everything-works
+++ b/test/make-sure-everything-works
@@ -1,10 +1,17 @@
 #!/bin/bash
 ./build-test-mh
 
-for file in *; do
-  [[ -x $file ]] && head -n1 $file | grep -q '^#!.*test-mh' && (echo running $file && ./$file >& /dev/null || exit 1)
-done
+fail() {
+  echo -e "\033[1;31m failed\033[0;0m"
+  exit 1
+}
 
-if [[ $? ]]; then
-  echo problem running $file
-fi
+ok() {
+  echo -e "\033[1;32m ok\033[0;0m"
+}
+
+for file in *; do
+  if [[ -x $file ]] && head -n1 $file | grep -q '^#!.*test-mh'; then
+    echo -n running $file && ./$file >& /dev/null && ok || fail $file
+  fi
+done
